main:main.c lcd.c touch.c parkingnum.c rfid.c key.c reserve.c message.c recharge.c beep.c
	arm-linux-gcc -o main main.c lcd.c touch.c parkingnum.c rfid.c key.c reserve.c message.c recharge.c beep.c -lpthread -std=gnu99
clean:
	rm main -rf